# Generated by Django 5.2.4 on 2025-08-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_files/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
