# Generated by Django 5.2.4 on 2025-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Solidworks', 'Solidworks'), ('Aspen', 'Aspen'), ('Articles', 'Articles')], default='blog', max_length=20),
        ),
    ]
